import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import Spinner from '../../components/Spinner';

type AspectRatio = "1:1" | "16:9" | "9:16" | "4:3" | "3:4";

const ImageGeneration: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('1:1');
  const [isLoading, setIsLoading] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [ai, setAi] = useState<GoogleGenAI | null>(null);

  useEffect(() => {
    if (process.env.API_KEY) {
      setAi(new GoogleGenAI({ apiKey: process.env.API_KEY }));
    }
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim() || isLoading || !ai) return;

    setIsLoading(true);
    setGeneratedImage(null);
    setError(null);

    try {
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio,
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        setGeneratedImage(`data:image/jpeg;base64,${base64ImageBytes}`);
      } else {
        setError("Image generation failed. No images were returned.");
      }
    } catch (err) {
      console.error("Image generation error:", err);
      setError("An error occurred while generating the image. Please check the console for details.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex-1 flex flex-col p-6 overflow-y-auto">
      <header className="mb-6">
        <h2 className="text-2xl font-bold text-white">Image Generation</h2>
        <p className="text-gray-400">Create stunning visuals with Imagen 4. Describe what you want to see.</p>
      </header>

      <form onSubmit={handleSubmit} className="space-y-4 mb-8">
        <div>
          <label htmlFor="prompt" className="block text-sm font-medium text-gray-300 mb-1">
            Prompt
          </label>
          <textarea
            id="prompt"
            rows={3}
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., A majestic lion wearing a crown, cinematic lighting, hyperrealistic"
            className="w-full bg-gray-800 border border-gray-600 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 text-white"
            disabled={isLoading || !ai}
          />
        </div>
        <div>
          <label htmlFor="aspectRatio" className="block text-sm font-medium text-gray-300 mb-1">
            Aspect Ratio
          </label>
          <select
            id="aspectRatio"
            value={aspectRatio}
            onChange={(e) => setAspectRatio(e.target.value as AspectRatio)}
            className="w-full bg-gray-800 border border-gray-600 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-indigo-500 text-white"
            disabled={isLoading || !ai}
          >
            <option value="1:1">Square (1:1)</option>
            <option value="16:9">Landscape (16:9)</option>
            <option value="9:16">Portrait (9:16)</option>
            <option value="4:3">Standard (4:3)</option>
            <option value="3:4">Tall (3:4)</option>
          </select>
        </div>
        <button
          type="submit"
          disabled={isLoading || !prompt.trim() || !ai}
          className="w-full bg-indigo-600 text-white font-bold py-3 px-5 rounded-lg disabled:bg-gray-600 disabled:cursor-not-allowed hover:bg-indigo-500 transition-colors flex items-center justify-center space-x-2"
        >
          {isLoading && <Spinner />}
          <span>{isLoading ? 'Generating...' : 'Generate Image'}</span>
        </button>
        {!ai && <p className="text-xs text-yellow-400 mt-2 text-center">API key not configured. Please set your API_KEY.</p>}
      </form>

      <div className="flex-1 flex items-center justify-center bg-gray-800/50 rounded-lg p-4">
        {isLoading && (
          <div className="text-center">
            <Spinner />
            <p className="mt-4 text-gray-400">Your image is being created...</p>
          </div>
        )}
        {error && <p className="text-red-400 text-center">{error}</p>}
        {generatedImage && (
          <div className="w-full max-w-lg">
            <img src={generatedImage} alt="Generated by AI" className="rounded-lg shadow-lg" />
          </div>
        )}
        {!isLoading && !error && !generatedImage && (
            <p className="text-gray-500">Your generated image will appear here.</p>
        )}
      </div>
    </div>
  );
};

export default ImageGeneration;
